site_name: ODMantic
site_description: AsyncIO MongoDB ODM (Object Document Mapper) using python type hinting
repo_name: art049/odmantic
repo_url: https://github.com/art049/odmantic

strict: true
docs_dir: .
site_dir: ../site

theme:
  name: material
  palette:
    primary: light green
    accent: light green
    scheme: preference
  icon:
    logo: material/spa
  features:
    - instant

extra_css:
  - css/extra.css

extra_javascript:
  - js/gitter.js
  - https://sidecar.gitter.im/dist/sidecar.v1.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 4
  - codehilite:
      linenums: true
      guess_lang: false
  - pymdownx.snippets:
      base_path: docs/examples_src
      check_paths: true # Fail when the document to include is not found
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji

plugins:
  - search
  - mkdocstrings:
      custom_templates: docs/api_reference/templates
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true
      watch:
        - odmantic/

nav:
  - Overview: index.md
  - fields.md
  - modeling.md
  - engine.md
  - querying.md
  - raw_query_usage.md
  - usage_fastapi.md
  - usage_pydantic.md
  - API Reference:
      - odmantic.model: ./api_reference/model.md
      - odmantic.engine: ./api_reference/engine.md
      - odmantic.query: ./api_reference/query.md
      - odmantic.field: ./api_reference/field.md
      - odmantic.reference: ./api_reference/reference.md
      - odmantic.bson: ./api_reference/bson.md
      - odmantic.fastapi: ./api_reference/fastapi.md
      - odmantic.exceptions: ./api_reference/exceptions.md
  - contributing.md
  - changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/art049
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/art049
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arthur-pastel-a08579112

google_analytics:
  - UA-180814888-1
  - auto
